### ISSUE TITLE
Несовместимость линтера и шаблонизатора

### ISSUE THREAD

**Issue by WIVSW** [yndx-shri-reviewer/task-3#1]
В этом задании нужно использовать шаблонизатор, который является результатом первого задания и линтер, который является результатом второго задания.

[В описании функции шаблонизации](https://github.com/yndx-shri-reviewer/task-1/blob/master/TEMPLATER.md) указано, что `Если в свойстве content блока вы описываете его элемент, то необходимо явно указывать название блока`
```
{
    block: 'my-block',
    content: {
        block: 'my-block',
        elem: 'my-block-element' // кстати по бэму, вроде как должно быть my-block__element
    }
}
```
Однако во всех примерах второго задания, это правило не соблюдается (полностью противоречит) и поле `elem` содержит только название элемента.
То есть когда в третьем задании мы подключим линтер и шаблонизатор, кто-то из-них (шаблонизатор) обязательно отвалится.
Что делать?

**Comment by dima117** [comment]
Формат BEMJSON, который используется в БЭМ-стеке разрешает не писать название блока (название блока будет взято из родительского узла. Например можно писать так:

```js
{
  block: 'b1', // b1
  content: {
    elem: 'e1',  // b1_e1
    content: 123
  }
}
```

Фраза "необходимо явно указывать название блока" означает, что рядом с полем "elem" всегда должно быть поле "block", в котором написано название блока. Указанный выше пример кода будет выглядеть так:

```js
{
  block: 'b1',
  content: {
    block: 'b1',
    elem: 'e1',
    content: 123
  }
}
```

Примеры из второго задания соответствуют этому условию.

**Comment by WIVSW** [comment]
Окей, не правильно, интерпретировал описание.
