### ISSUE TITLE
Возвращаемые значения линтера

### ISSUE THREAD

**Issue by bo4arovpavel1989** [yndx-shri-reviewer/task-3#2]
Линтер из второго задания должен возвращать положение блока в виде
 ```.location:  {start:  {line,  column}, end:  {line, column} }```.
В третьем задании для подсветки ошибочных блоков необходимо для start и end значения offset. Если я добавляю их в линтер, то перестают проходить тесты второго задания на правильное положение блока. Т.е. в данном случае приходится изменять линтер из второго задания, чтобы он корректно работал в третьем, в принципе ничего страшного, просто немного противоречит общему принципу - создания единой инфраструктуры для разработки.

**Comment by dima117** [comment]
Вы правы. Данные на выходе из линтера должны соответствовать формату, описанному во втором задании. Иначе автотесты не пройдут.

Есть большое количество способов интеграции линтера с плагином VS Code. Вы можете выбрать любой на своё усмотрение. Более лаконичный способ будет предпочтительнее, чем более громоздкий.
