### ISSUE TITLE
Severity: Hint - должно ли быть визуальное представление?

### ISSUE THREAD

**Issue by chrstnv** [yndx-shri-reviewer/task-3#5]
Подскажите, пожалуйста, должно ли быть визуальное представление у проверки с Severity: Hint? Для Error, Warning, Information всё работает корректно, подчеркивается некорректный участок json, появляется конфликт в problems, а для hint ничего нет, пытаюсь понять — так by design или нужно разбираться, как исправить.

**Comment by dima117** [comment]
Да, это стандартное поведение - предупреждения с типом `Hint` отображаются только в редакторе. Сходу не нашел описание этой особенности. Нашел упоминания об этом:
- [changelog](https://code.visualstudio.com/updates/v1_22#_hints-in-the-editor)
- [issue](https://github.com/microsoft/vscode/issues/45436#issuecomment-372616323)

**Comment by dima117** [comment]
Отображение в редакторе зависит от темы. У меня отображается в виде трех точек в начале блока. 

![image](https://user-images.githubusercontent.com/5608639/60989001-9179d200-a34d-11e9-85e3-e8cb35cf33ff.png)

**Comment by chrstnv** [comment]
Спасибо, нашла, уж очень незаметно было :)
![image](https://user-images.githubusercontent.com/17298953/60990941-3696a980-a352-11e9-8628-cc1fee51ebba.png)
