### ISSUE TITLE
Правило "в каждом объекте должно быть поле block" из линтера-заглушки

### ISSUE THREAD

**Issue by NazarkinRoman** [yndx-shri-reviewer/task-3#6]
Должно ли это правило применяться к объектам-модификаторам `mods`? Сейчас это выглядит вот так:

<img width="349" alt="Extension Development Host  - page json — vscode-shri-test-project 2019-07-12 18-23-40" src="https://user-images.githubusercontent.com/1572715/61124830-332a2c00-a4d2-11e9-9acb-4e9c8129b39b.png">

Валидно ли такое поведение или нужно исправить?

**Comment by dima117** [comment]
Требования к узлу дерева, на котором нужно отображать ошибку, описаны во втором задании. Если линтер проходит тесты второго задания, то считайте, что всё сделано правильно.

Кажется, в условии второго задания написано, что нужно подсвечивать весь блок.

**Comment by dima117** [comment]
Извините, я сначала неправильно понял вопрос. Думал, то он относится к линтеру из второго задания.

Правило "в каждом узле должно быть поле `block`" проверяет именно это условие и оно корректно подсвечивает узел с модификаторами. Эта ситуация не является ошибкой.

**Comment by NazarkinRoman** [comment]
@dima117 понял, спасибо.
