### ISSUE TITLE
Вопрос насчет jsonMain.ts

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-3#8]
Этот файл вообще нужен для выполнения задания? У меня дизайн-система и линтер и без него работают. Или это какое-то задание со звездочкой: разобраться, что он делает, и добавить его в плагин?

**Comment by dima117** [comment]
Добрый день!

Пожалуйста, внимательно прочитайте условия задания и проверьте, что в вашей работе они выполнены.

**Comment by SkyFlame00** [comment]
@dima117 Условия насчет дизайн-системы, линтера и настроек я выполнил. Но в задании нет ничего, что могло бы намекать на использование jsonMain.ts. Последние два дня я пытался разобраться в нем, но даже до сих пор до конца не могу понять, что он делает, кроме того, что что-то должно валидироваться на предмет соответствия JSON-схемам. Все стопорится на моменте, когда клиент отправляет 'json/validate' (`client.sendRequest(ForceValidateRequest.type, activeDocUri`) на сервер впустую, потому что серверной реализации для обработки запроса этого LSP-метода просто нет. Серверная реализация есть только для линтера. Поэтому я делаю вывод, что этот файл либо совсем не нужен для задания, либо нужно найти в нем хоть какие-то (некоторые я нашел, что позволило мне добраться до отправки запроса на сервер).

**Comment by dima117** [comment]
Этот файл находится в репозитории потому, что является частью задания. Не могу вам подсказать, что с ним делать, т. к. это облегчит выполнение задания. Советую прочитать еще раз условия задания и принять решения исходя из того, что там написано.
