### ISSUE TITLE
Линтер из второго задания

### ISSUE THREAD

**Issue by WIVSW** [yndx-shri-reviewer/task-3#9]
Я уже сдал задание, но насколько я понял из  https://github.com/yndx-shri-reviewer/task-1/issues/94 https://github.com/yndx-shri-reviewer/task-1/issues/96 задание можно доработать.

Если доработать нельзя, то вопросы не актуальны.

**Вопросы:**
1. В условии с линтером указано, что:
```
Сейчас плагин использует линтер-заглушку, проверяющий всего два правила: 1) «запрещены названия полей в верхнем регистре»; 2) «в каждом объекте должно быть поле block». Подключите в проект линтер из второго задания.
```
Значит ли это, что линтер-заглушка и линтер из второго задания должно работать вместе.
Я сначала подумал, что нужно заменить заглушку своим линтером, также как и в первом условии.

2. В условии с настройками указано, что 
`При изменении конфигурации новые настройки должны применяться к работе линтера.`
это распространяется только на указанные в задании настройки или нужно правила из второго задания тоже сделать конфигуриемыми?

**Comment by dima117** [comment]
1. Не принципиально (кстати, уже [был](https://github.com/yndx-shri-reviewer/task-3/issues/4) такой вопрос)
2. Смысл задания - исправить ошибки. Все ошибки сделаны в коде, который дается вместе с условием задания.

**Comment by WIVSW** [comment]
Спасибо за очень быстрый ответ.
> * Не принципиально (кстати, уже [был](https://github.com/yndx-shri-reviewer/task-3/issues/4) такой вопрос)

Извиняюсь, за дубль.
> * Смысл задания - исправить ошибки. Все ошибки сделаны в коде, который дается вместе с условием задания.
Это-то да, но некоторые ошибки перестанут воспроизводится заменой модуля.
Просто странно как-то:
1. Делаю коммит с фиксом ошибки
2. Делаю еще один коммит с заменой линтера, который выпиливает старый линтер и ошибка перестанет воспроизводится и теперь не понятно зачем я делал предыдущий коммит с фиксом.
